services:
  # Веб-сервис для бота
  - type: web
    name: magnum-star-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        value: https://magnumstarbot.onrender.com
      - key: PORT
        value: 10000
    autoDeploy: true